# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplachScreen(object):
    def setupUi(self, SplachScreen):
        SplachScreen.setObjectName("SplachScreen")
        SplachScreen.resize(680, 400)
        self.centralwidget = QtWidgets.QWidget(SplachScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(56, 58, 89);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.label_title = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_title.setGeometry(QtCore.QRect(4, 80, 651, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("/*color: rgb(229, 152, 155);*/\n"
"color: rgb(112, 160, 175);\n"
"color: rgb(191, 204, 181);")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_description = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_description.setGeometry(QtCore.QRect(0, 160, 651, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet("/*color: rgb(181, 131, 141);*/\n"
"color: rgb(229, 152, 155);\n"
"color: rgb(191, 204, 181);\n"
"color: rgb(112, 160, 175);\n"
"\n"
"background: none;")
        self.label_description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description.setObjectName("label_description")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(40, 260, 581, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"\n"
"\n"
"    background-color: rgb(85, 88, 135);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"    \n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.494, x2:0, y2:0.506, stop:0 rgba(159, 105, 108, 255), stop:1 rgba(229, 152, 155, 255));\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.494, x2:0, y2:0.506, stop:0 rgba(112, 160, 175, 255), stop:1 rgba(229, 152, 155, 255));\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.494, x2:0, y2:0.506, stop:0 rgba(112, 160, 175, 255), stop:1 rgba(191, 204, 181, 255));\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.494, x2:0, y2:0.506, stop:0 rgba(94, 136, 148, 255), stop:1 rgba(191, 204, 181, 255));\n"
"\n"
"}")
        self.progressBar.setProperty("value", 60)
        self.progressBar.setObjectName("progressBar")
        self.label_loading = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_loading.setGeometry(QtCore.QRect(0, 280, 651, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("color: rgb(181, 131, 141);\n"
"color: rgb(191, 204, 181);\n"
"color: rgb(112, 160, 175);\n"
"background: none;")
        self.label_loading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_loading.setObjectName("label_loading")
        self.verticalLayout.addWidget(self.dropShadowFrame)
        SplachScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplachScreen)
        QtCore.QMetaObject.connectSlotsByName(SplachScreen)

    def retranslateUi(self, SplachScreen):
        _translate = QtCore.QCoreApplication.translate
        SplachScreen.setWindowTitle(_translate("SplachScreen", "MainWindow"))
        self.label_title.setText(_translate("SplachScreen", "<strong>Plagiat</strong>Scanner"))
        self.label_description.setText(_translate("SplachScreen", "<strong>Plagiat</strong>Scanner"))
        self.label_loading.setText(_translate("SplachScreen", "<html><head/><body><p>Chargement...</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplachScreen = QtWidgets.QMainWindow()
    ui = Ui_SplachScreen()
    ui.setupUi(SplachScreen)
    SplachScreen.show()
    sys.exit(app.exec_())
